### ISSUE TITLE
More apps from author doesn't show all the results that you see in the website

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer-scope#1]
After updating to v1.5, I clicked on *Telegram* made by *Ubuntu Core App Developers* who has uploaded atleast 19 apps like Clock, Calendar, Weather, Telegram, Gallery etc. In the website I see all of them. But on the scope, I see only 11 apps. Not sure why.

**Comment by bhdouglass** [comment]
The scope currently only shows the first 10ish results, I'm not sure if there is a good way to page the results in a scope. I may just up the results to 20 or 30, but we shall see.

**Comment by krnekhelesh** [comment]
ah ok..to be fair, very few app devs have more than 10 apps ;). So its a really low priority issue.

**Comment by bhdouglass** [comment]
Well, it's also only showing 10 results for any search result, so it might be nicer to show more.

**Comment by bhdouglass** [comment]
Just upped it to 20 results in v1.6
