### ISSUE TITLE
More Apps from Author shows results from other app developers

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer-scope#2]
I clicked on *Dekko* made by *Dan Chapman* and when clicking on More apps, it shows Cinema, MixCloud etc which were not made by Dan Chapman. Infact Dan Chapman has only uploaded Dekko.

**Comment by bhdouglass** [comment]
Turns out the query was only using the first part of the name (before the space). I'll need to url encode the spaces for it to work (apparently go doesn't help me out here :) ).

**Comment by bhdouglass** [comment]
Fixed in v1.6!
