### ISSUE TITLE
Widgets with duplicated ID crashes Dash with latest rc-proposed

### ISSUE THREAD

**Issue by stolowski** [bhdouglass/uappexplorer-scope#6]
The preview code pushes two widgets with "author" ID and that makes the Dash crash with latest changes to the preview handling code in the Dash. This is obviously a bug in the dash and I'm going to fix that (https://bugs.launchpad.net/ubuntu/+source/unity-scopes-shell/+bug/1581495) but at the same time the scope needs fixing too, as otherwise weird things will happen anyway (most likely you will see one of the widgets but not both, one will be discarded).

I'm not sure when the Dash fix lands, it would be best if you land the fix as soon as possible as Ubuntu Store is not bound by OTA cycles.

**Comment by bhdouglass** [comment]
Thank you for finding this! I'll get it fixed asap.

**Comment by bhdouglass** [comment]
I've just pushed an update to the store, this should be fixed now.
